# Generated by Django 4.2.8 on 2026-02-17 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('blood_sugar', 'Blood Sugar'), ('temperature', 'Temperature'), ('weight', 'Weight')], max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Management'), ('fitness', 'Fitness'), ('sleep', 'Sleep Improvement'), ('stress', 'Stress Reduction'), ('nutrition', 'Nutrition'), ('hydration', 'Hydration')], max_length=20)),
                ('description', models.TextField()),
                ('target_value', models.CharField(help_text="e.g., '10000 steps/day'", max_length=100)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('very_bad', 'Very Bad'), ('bad', 'Bad'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=20)),
                ('energy_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('sleep_hours', models.FloatField(help_text='Hours of sleep', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('exercise_minutes', models.IntegerField(default=0, help_text='Minutes of exercise', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_intake', models.IntegerField(default=0, help_text='Water intake in ml', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Any additional health notes')),
                ('symptoms', models.TextField(blank=True, help_text='Any symptoms experienced')),
                ('meals_logged', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('check_in_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Check-ins',
                'ordering': ['-check_in_date'],
                'unique_together': {('user', 'check_in_date')},
            },
        ),
    ]
